/*
RECOVERY MODEL TO FULL.
PERFORM INSERT WITH TABLOCK HINT ON A HEAP TABLE.
RESET AND CREATE THE SAME ENVIRONMENT TO PERFORM INSERT WITH (TABLOCK) HINT
*/

SET STATISTICS TIME, IO ON

SET NOCOUNT ON

ALTER DATABASE DBATEST SET RECOVERY FULL;

SELECT name, recovery_model_desc from sys.databases WHERE name='DBATEST';

USE DBATEST
GO
TRUNCATE TABLE dbo.t2

CHECKPOINT

/*VERIFY THAT ENVIRONMENT IS RESET*/


/*
VERIFY LOGGED ROWS
*/
SELECT Operation, COUNT(*) as Count
FROM sys.fn_dblog(NULL, NULL) 
WHERE
    Operation IN (N'LOP_INSERT_ROWS', 'LOP_FORMAT_PAGE')
   GROUP BY OPERATION 
   ORDER BY COUNT(*) DESC

   -- VERIFY ROW COUNTS
SELECT COUNT(*) AS t1_COUNT FROM dbo.t1;
SELECT COUNT(*) AS t2_COUNT FROM dbo.t2;

/*
PERFORM INSERT WITH TABLOCK HINT
*/

INSERT INTO t2 WITH (TABLOCK) (id,a,b)
SELECT * FROM t1





/*
** 'LOP_INSERT_ROWS'= NUMBER OF INSERT RECORDS TRACKED IN T-LOG 
** 'LOP_FORMAT_PAGE'= NUMBER OF PAGES FORMATTED
*/
SELECT Operation, COUNT(*) as Count
FROM sys.fn_dblog(NULL, NULL) 
WHERE
    Operation IN (N'LOP_INSERT_ROWS', 'LOP_FORMAT_PAGE')
   GROUP BY OPERATION 
   ORDER BY COUNT(*) DESC



/*SET RECOVERY BACK TO SIMPLE*/
ALTER DATABASE DBATEST SET RECOVERY SIMPLE;
